Onto-DESIDE-VSE/patomat2

- .gitignore
- pom.xml
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/Constants.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/PatOMat2Application.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/AppConfig.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/ApplicationConfig.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/SecurityConfig.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/SessionCleanupListener.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/exception/InvalidFileException.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/exception/OntologyNotUploadedException.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/exception/PatOMat2Exception.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/OntologyController.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/handler/ErrorInfo.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/handler/RestExceptionHandler.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/FileStorageService.java
- src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyService.java
- src/main/resources/application.properties
- src/main/resources/application.yml
> Enhancement#1 ontology upload

- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/event/OntologyFileUploadedEvent.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/MatchService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyStoringService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jOntologyHolder.java
> [GH-10] Reset cached matches and loaded ontology on new files upload

- backend/pom.xml
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/Constants.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/SessionCleanupListener.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/event/OntologyFileUploadedEvent.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/exception/PatternParserException.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/Pattern.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternMatch.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/ResultBinding.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/PatternMatchesController.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/MatchService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyStoringService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/pattern/PatternParser.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jOntologyHolder.java
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternTest.java
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/service/pattern/PatternParserTest.java
- backend/src/test/resources/pattern-example.json
- frontend/src/components/MatchesTable.vue
- frontend/src/components/OntologyImport.vue
- frontend/src/views/ImportView.vue
> Enhancement#12 pattern file reading

- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/Constants.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/ApplicationConfig.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/exception/AmbiguousOntologyException.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/NewEntityGenerator.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/Pattern.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternInstance.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternMatch.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/PatternMatchesController.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/handler/RestExceptionHandler.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/MatchService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jNewEntityGenerator.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jOntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jSparqlQueryBuilder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/util/Rdf4jSparqlQueryBuilder.java
- backend/src/main/resources/application.yml
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/environment/Generator.java
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternTest.java
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jNewEntityGeneratorTest.java
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jOntologyHolderTest.java
- backend/src/test/resources/archivo-partial.nt
- frontend/src/components/MatchesTable.vue
> Enhancement#13 generate transformation inserts

- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/Pattern.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternInstance.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/MatchService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/util/Rdf4jSparqlQueryBuilder.java
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternTest.java
- frontend/src/components/MatchesTable.vue
- frontend/src/types/PatternInstance.ts
> Enhancement#14 generate sparql deletes

- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/NameTransformation.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/NewEntity.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/Pattern.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternInstance.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternInstanceTransformation.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/TransformationSpecification.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/OntologyStoringController.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/TransformationController.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/MatchService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/TransformationService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jOntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/util/FileAwareByteArrayResource.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/util/Utils.java
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jOntologyHolderTest.java
- frontend/package-lock.json
- frontend/src/components/MatchesTable.vue
- frontend/src/types/PatternInstanceTransformation.ts
- frontend/src/util/Utils.ts
- frontend/src/views/ImportView.vue
- frontend/src/views/PatternMatches.vue
> Enhancement#16 apply transformation

- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/MatchService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/TransformationService.java
- frontend/src/components/OntologyImport.vue
- frontend/src/views/PatternMatches.vue
> Enhancement#23 error handling

- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternInstance.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternInstanceTransformation.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/MatchService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyStoringService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/TransformationService.java
- frontend/.prettierrc.json
- frontend/package.json
- frontend/src/components/EditableLabel.vue
- frontend/src/components/MatchesTable.vue
- frontend/src/components/OntologyImport.vue
- frontend/src/types/PatternInstance.ts
- frontend/src/views/PatternMatches.vue
> Enhancement#21 editable new entity label

- README.md
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/Constants.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/AppConfig.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/ApplicationConfig.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/InvalidSessionTracker.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/SecurityConfig.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/SessionCleanupListener.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/config/SessionCountingAnonymousFilter.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/Pattern.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/FileStorageService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyStoringService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/pattern/PatternParser.java
- backend/src/main/resources/application.yml
- backend/src/test/java/cz/cvut/kbss/ontodeside/patomat2/model/PatternTest.java
- docker-compose.yml
- frontend/src/components/MatchesTable.vue
- frontend/src/components/OntologyImport.vue
- frontend/src/views/PatternMatches.vue
> Enhancment#8 security

- CHANGELOG.md
- docker-compose.yml
- frontend/package-lock.json
- frontend/package.json
- frontend/src/assets/CHANGELOG.md
- frontend/src/components/Changelog.vue
- frontend/src/views/AboutView.vue
- frontend/vite.config.ts
> [Enhancement #29] Add changelog accessible from the application About page

- frontend/src/components/MatchesTable.vue
> [GH-31] Highlight new entities in the SPARQL INSERT query.

- LICENSE
- README.md
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/OntologyDiff.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/TransformationResult.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/model/TransformationSummary.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/TransformationController.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/rest/handler/RestExceptionHandler.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/OntologyStoringService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/TransformationService.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/TransformedOntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/service/rdf4j/Rdf4jOntologyHolder.java
- backend/src/main/java/cz/cvut/kbss/ontodeside/patomat2/util/Utils.java
- frontend/src/assets/CHANGELOG.md
- frontend/src/components/TransformationSummaryView.vue
- frontend/src/types/TransformationSummary.ts
- frontend/src/views/PatternMatches.vue
> Enhancement#33 transformation summary

- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/Pattern.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/service/pattern/PatternParser.java
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/model/PatternTest.java
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/service/pattern/PatternParserTest.java
- backend/src/test/resources/pattern-example.json
- frontend/src/assets/CHANGELOG.md
- frontend/src/components/OntologyImport.vue
- frontend/src/views/PatternMatches.vue
> Enhancement#43 filter expressions

- frontend/src/assets/CHANGELOG.md
- frontend/src/components/MatchesStatistics.vue
- frontend/src/components/MatchesTable.vue
- frontend/src/types/PatternMatchStatistics.ts
- frontend/src/views/PatternMatches.vue
> Enhancement#45 statistics filters of matches

- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/Constants.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/EntityLabel.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/NewEntity.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/PatternInstanceTransformation.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/service/rdf4j/Rdf4jNewEntityGenerator.java
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/model/NewEntityTest.java
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/model/PatternTest.java
- frontend/src/components/EditableLabel.vue
- frontend/src/components/LabelEditDialog.vue
- frontend/src/constants/Constants.ts
- frontend/src/types/PatternInstance.ts
> Enhancement#46 labels preflabels altlabels

- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/LoadedTransformationInput.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/PatternInfo.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/TransformationInput.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/rest/OntologyStoringController.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/rest/TransformationController.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/service/OntologyStoringService.java
- frontend/src/api/OntologyStorageApi.ts
- frontend/src/components/LoadedTransformationInputInfo.vue
- frontend/src/components/MatchesStatistics.vue
- frontend/src/types/LoadedTransformationInput.ts
- frontend/src/views/PatternMatches.vue
> Bug#56 no match patterns in statistics

- README.md
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/config/ApplicationConfig.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/config/SessionCleanupListener.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/model/TransformationInput.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/rest/ExampleController.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/rest/OntologyStoringController.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/rest/handler/RestExceptionHandler.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/service/ExampleService.java
- backend/src/main/java/cz/vse/swoe/ontodeside/patomat2/service/OntologyStoringService.java
- backend/src/main/resources/application.yml
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/rest/BaseControllerTestRunner.java
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/rest/ExampleControllerTest.java
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/rest/OntologyStoringControllerTest.java
- backend/src/test/java/cz/vse/swoe/ontodeside/patomat2/service/ExampleServiceTest.java
- docker-compose.yml
- frontend/src/api/OntologyStorageApi.ts
- frontend/src/assets/CHANGELOG.md
- frontend/src/components/importing/LoadedTransformationInputInfo.vue
- frontend/src/components/importing/OntologyImportUrls.vue
- frontend/src/components/importing/TransformationExamples.vue
- frontend/src/components/match/MatchesStatistics.vue
- frontend/src/views/AboutView.vue
- frontend/src/views/HomeView.vue
- frontend/src/views/PatternMatches.vue
- frontend/src/views/TransformationInputView.vue
> Enhancement#52 allow providing transformation example

- frontend/src/api/OntologyStorageApi.ts
- frontend/src/assets/CHANGELOG.md
- frontend/src/components/importing/OntologyImportFiles.vue
- frontend/src/components/importing/OntologyImportUrls.vue
- frontend/src/types/PatternInstanceTransformation.ts
- frontend/src/views/PatternMatches.vue
> Enhancement#38 automatically apply transformation

- frontend/src/components/match/BindingValue.vue
- frontend/src/components/match/MatchesTable.vue
- frontend/src/components/match/SparqlWithVariables.vue
- frontend/src/constants/Constants.ts
- frontend/src/util/Utils.ts
> Enhancement#61 variables in sparql

- backend/src/main/resources/application.yml
- docker-compose.yml
> swagger api docs url

- frontend/src/components/match/MatchesTable.vue
> hide sorting select in case of no backend sorting methods loaded
